{% set name = "image-meta-tag" %}
{% set version = "0.7.8" %}
{% set giturl = "https://github.com/SciTools-incubator/image-meta-tag" %}
{% set sha256 = "5a79fbe5901e59ae5b7d02a3c1985fb42cefa21b136806b9e36baaf6317e6d22" %}

package:
  name: image-meta-tag
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: {{ giturl }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
      - python
      - setuptools
  run:
      - python
      - matplotlib-base
      - numpy
      - pillow

test:
  imports:
      - ImageMetaTag

about:
  home: https://github.com/SciTools-incubator/image-meta-tag
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image metadata tagging, database and presentation
  description: |
    ImageMetaTag is a python package built around a wrapper for savefig in matplotlib,
    which adds metadata tags to supported image file formats.
    Once the images have been tagged, it can also be used to manage an SQL database of
    images and their metadata. The image metadata can be used to produce an
    ImageMetaTag.ImageDict object: a structured/heirachical dictionary of dictionaries which
    can be used to easily create web pages to present large numbers of images.
  doc_url: http://scitools-incubator.github.io/image-meta-tag/build/html/index.html
  dev_url: https://github.com/SciTools-incubator/image-meta-tag

extra:
  recipe-maintainers:
    - malcolmbrooks
