travis:
  secure:
    BINSTAR_TOKEN: X5kSyexkJ3/vEd2rRd6pqMRnyZqnjj6z5cEqrDrZLTOh6w6iyBNuaRd8XklFtssNbynGc6h2FeoAAOJv8CJW7AFFLusRRY4/3Bp5K4RSXNHtjCd/AJdQODpORxQwczj24j5AODscaqhu9IBZW3ifPsRMSOgjDhnoGj/6WS515q3JMbuYcN1GCHg5tDk0PnEEB3X2/Bdfum3keYhoZDJbHKR+wRdARWl2qv2gBTN9wcM25UUC7frRZLxKd5taQ9Y+IPl3Y/yUMqYu30zRrAQZTx5TQV+PjdoMUmW51rIXgTAJHj93RsXHVNJ1QnCW+KbGAe3ahtRVo8k+tuSCKKC3QGfjd+ICPdpuZI6tJcWUnv6pI8+7Z2/taGzIwPnDRYe+gEZqX/I9fU3RKHy42D/CDqp60ZBxVl6tIuMfJdsmgOKSk6QMWiieyDExm3V+HzOGY2N29OOYmiTbz+O3cvNmZRu2HaYmb9pNWHnzwHiGQiZ/B8fjq4Fii9kY/HnJRS4SKreT+5yE7oT6S9s0xU+S0cVzXimsGDgIMBFH0s7ocGJ6hPAbAP+DiPE5f5D+KcsaG9lmnMdnaR7k3BiSZsqZyiUbkShK9Qa0RyaRYvvTLeNbIp0pxXAWo/JuagjOGcjT3WIr9NUfMxVF/1eKhTZEndQQytsn3leqGOkQ/HTAJAY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
