travis:
  secure:
    BINSTAR_TOKEN: RcC2mSsHIZs0l0DWjtoMiAtI0w1sZyRBATClXQvrukNSh0gOv2XDC6s7wyvLlv4B5NI7nyxzaYSqGeBHTVi8ZXH50YHaVqkszaWsN5/3FoM2Zp8VQ+RSwjO+gtsJTqoFriN70KAaymyAdTSgIA4HSezg4p0bOqCCVRVik2qq4gbfbcHR3ArAApXs/GVP7L+sbXfZvhHDX2gRlQGksHT0gh+ha+ehSar8nboDZPXIkOumYjfEsrmTs5EIsBY1n0sKC31jXKAzHkCSg7fWYbtI0T5hYgMoUbQ/W7GUs7ASYNtAIaizDn5Q5Z5KO7SKbiaKTMO08G2PHNAhB0sYIuw87LM0+MfQsQfC9JhsN2rqwN/Qq2DXBAnJGMXPF4MMAgfNhDbZcmPZIghqQ1PPO4YAMPA0NBMB8d1t1bpbV0sWEJ1efVVSiygaAzXVIVwsOwCLml+Br7PzwU5XWZMwMRH3+lsoWIjUmmO/ymL2+vkeJVDE7uIEvO+hEPEXoQceN0B+USbRzVclMxLnNEPmQ6dvYRNkXEepO9ia0TYEIOOD6dLgnRLHZ1TUICcWvvewvh89KXt0f4hWURIXBaGSZ1I9NvgncEd8++wq8a+IH0cNe1mWwj6AAn9/OB46GVF16T7Oz8eysijwrpXg4lcHxK+WrlxYy0fOeOJ1dUgEweH06wI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
